[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
broadcast = 'records'
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 200
auto_detect_solc = true
evm_version = "prague"
via-ir = false
remappings = [
    '@base-contracts/=lib/contracts/',
    'forge-std/=lib/forge-std/src/',
    'interfaces/L1/=lib/contracts/interfaces/L1/',
    'interfaces/legacy/=lib/contracts/interfaces/legacy/',
    'interfaces/universal/=lib/contracts/interfaces/universal/',
    'src/libraries/=lib/contracts/src/libraries/',
]

[profile.nitro-deploy]
optimizer = true
optimizer_runs = 10000
bytecode_hash = "none"
evm_version = "cancun"

[profile.tee-registry-deploy]
optimizer = true
optimizer_runs = 999999
bytecode_hash = "none"
evm_version = "cancun"

[lint]
lint_on_build = false
