[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
broadcast = 'records'
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 200
auto_detect_solc = true
evm_version = "prague"
via-ir = false
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
    '@base-contracts/=lib/contracts/',
    '@solady/=lib/solady/src/',
    '@solady-v0.0.245/=lib/solady-v0.0.245/src/',
    'forge-std/=lib/forge-std/src/',
    'interfaces/dispute/=lib/contracts/interfaces/dispute/',
    'interfaces/L1/=lib/contracts/interfaces/L1/',
    'interfaces/legacy/=lib/contracts/interfaces/legacy/',
    'interfaces/multiproof/=lib/contracts/interfaces/multiproof/',
    'interfaces/universal/=lib/contracts/interfaces/universal/',
    'src/libraries/=lib/contracts/src/libraries/',
    'src/dispute/=lib/contracts/src/dispute/',
    'src/universal/=lib/contracts/src/universal/',
    'lib/op-enclave/=lib/op-enclave/',
    'openzeppelin/=lib/risc0-ethereum/lib/openzeppelin-contracts/',
]
